GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u004",
    "name": "Deuclana",
    "email": "deulana@email.com",
    "password": "ciclana123"
}
###